# rubocop:disable Metrics/AbcSize
# rubocop:disable all
# TODO - FIX COP
# rubocop:enable all

AllCops:
  TargetRubyVersion: 2.0
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'script/**/*'
    - 'Rakefile'
    - 'Gemfile'
    - 'Guardfile'
    - 'config/initializers/*'
    - 'config/application.rb'
    - 'config/unicorn.rb'
    - 'tmp.rb'
    - 'scratch.rb'
    - 'lib/assets/**/*'

# Disable documentation cops
Documentation:
  Enabled: false

Style/MultilineOperationIndentation:
  Enabled: false

Metrics/ClassLength:
  Max: 180

Metrics/MethodLength:
  Max: 16

Metrics/LineLength:
  Max: 180
  Exclude:
    - 'spec/features/*'

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
  Enabled: false
